language: python

python:
  - "3.6"

addons:
  postgresql: "11"

install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database favorite_things_test;' -U postgres

script:
  - pytest
  - cd ./client
  - npm install
  - npm run test
