# Generated by Django 2.2.3 on 2019-08-03 14:20

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=30, unique=True),
        ),
    ]
