export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const ADD_DUMMY_CATEGORY = 'ADD_DUMMY_CATEGORY';
export const DELETE_DUMMY_CATEGORY = 'DELETE_DUMMY_CATEGORY';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';

export const ADD_FAVORITE_THING = 'ADD_FAVORITE_THING';
export const UPDATE_FAVORITE_THING = 'UPDATE_FAVORITE_THING';
export const DELETE_FAVORITE_THING = 'DELETE_FAVORITE_THING';
